BILL-005: Delete accounts endpoint
oaraujocesar/bill-api pull request #3
Opened 2024-11-07 22:48 UTC by oaraujocesar

2024-11-07 23:02 UTC, caiofsr requested changes

2024-11-07 23:02 UTC, caiofsr commented on src/application/use-cases/account/delete.ts
> +			status: 200,
```suggestion
			status: HttpStatus.NO_CONTENT,
```

2024-11-09 20:30 UTC, oaraujocesar commented on src/application/repositories/account.repository.ts
> +	deleteAccount(serial: ULID): Promise<void>
pode ser tambem. O ULID mapeia string entao tecnicamente da no msm

2024-11-09 20:30 UTC, oaraujocesar commented on src/application/repositories/account.repository.ts
> +	deleteAccount(serial: ULID): Promise<void>
so fica mais semantico

2024-11-09 23:07 UTC, caiofsr approved these changes
LGMT 🚀

2024-11-10 14:30 UTC, merged